import { BuryCommand } from './bury';
import { DeleteCommand } from './delete';
import { IgnoreCommand } from './ignore';
import { PauseTubeCommand } from './pause-tube';
import { PutCommand } from './put';
import { ReleaseCommand } from './release';
import { ReserveCommand } from './reserve';
import { ReserveJobCommand } from './reserve-job';
import { ReserveWithTimeoutCommand } from './reserve-with-timeout';
import { StatsCommand } from './stats';
import { UseCommand } from './use';
import { WatchCommand } from './watch';

export * from './bury';
export * from './command';
export * from './delete';
export * from './pause-tube';
export * from './put';
export * from './release';
export * from './reserve';
export * from './reserve-job';
export * from './reserve-with-timeout';
export * from './stats';
export * from './use';
export * from './watch';

export const bury = new BuryCommand();
export const del = new DeleteCommand();
export const ignore = new IgnoreCommand();
export const pauseTube = new PauseTubeCommand();
export const put = new PutCommand();
export const release = new ReleaseCommand();
export const reserve = new ReserveCommand();
export const reserveJob = new ReserveJobCommand();
export const reserveWithTimeout = new ReserveWithTimeoutCommand();
export const stats = new StatsCommand();
export const use = new UseCommand();
export const watch = new WatchCommand();
